language: python
python: 3.8

dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.4
      - python3.5
      - python3.6
      - python3.7
      - pypy

install:
  - pip install -r requirements_dev.txt
  - pip install -e .
  
script:
  - pytest --cov=graphql_from_struct --cov-report term
  - sphinx-build -b html docs/source/ docs/build/

after_success:
  bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: always

